name: hospital_massage_system
description: "Hospital Massage Workshop Management System - A professional mobile application for managing massage therapy appointments in healthcare environments."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Functional Programming
  dartz: ^0.10.1
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Networking & Backend
  supabase_flutter: ^2.0.0
  http: ^1.1.0
  
  # UI Components
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.8
  
  # Navigation
  go_router: ^12.0.0
  
  # Forms & Validation
  formz: ^0.6.1
  
  # Date & Time
  intl: ^0.19.0
  
  # Notifications
  flutter_local_notifications: ^16.1.0
  
  # PDF Generation
  pdf: ^3.10.4
  printing: ^5.11.0
  
  # Security
  crypto: ^3.0.3
  
  # Accessibility
  flutter_accessibility_service: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  # Add assets for the hospital theme
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/fonts/

  # Custom fonts for healthcare theme will be added here
  # fonts:
  #   - family: HospitalFont
  #     fonts:
  #       - asset: assets/fonts/HospitalFont-Regular.ttf
  #       - asset: assets/fonts/HospitalFont-Bold.ttf
  #         weight: 700
